---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 4
        memory: 1536
      network:
        - - private_network
          - ip: '192.168.33.10'

suites:
  - name: remotezk
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[baragon::server]
      - recipe[nginx]
      - recipe[baragon::agent]
    attributes:
      java:
        jdk_version: 7
  - name: remotezk-source
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[baragon::server]
      - recipe[nginx]
      - recipe[baragon::agent]
    attributes:
      java:
        jdk_version: 7
      baragon:
        install_type: source
  - name: localzk
    run_list:
      - recipe[java]
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::server]
      - recipe[baragon::agent]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
        - 'localhost:2181'
      java:
        jdk_version: 7
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true
  - name: localzk-source
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::server]
      - recipe[baragon::agent]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
        - 'localhost:2181'
        install_type: source
      java:
        jdk_version: 7
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true
